[run]
init_cmds = [
  ["make", "build"],
	["./bin/grafana", "web"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/pkg",
	"$WORKDIR/grafana/src/views",
	"$WORKDIR/conf",
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
	["make", "build"],
	["./bin/grafana", "web"]
]
