[run]
init_cmds = [
  ["go", "build", "-o", "./bin/grafana"],
	["./bin/grafana", "web"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/pkg",
	"$WORKDIR/src/views",
	"$WORKDIR/conf",
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
  ["go", "build", "-o", "./bin/grafana"],
	["./bin/grafana", "web"]
]
