version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\grafana\grafana

environment:
  GOPATH: c:\gopath

install:
  - choco install mingw
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go run build.go setup

build_script:
  - go run build.go build
