version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\grafana\grafana

environment:
  nodejs_version: "6"
  GOPATH: c:\gopath

install:
  # install nodejs and npm
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install --pure-lockfile
  - npm install -g grunt-cli
  # install gcc (needed for sqlite3)
  - choco install -y --limit-output mingw
  - set PATH=C:\tools\mingw64\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go run build.go setup

before_build:
  - cmd: if NOT "%buildTag%"=="" echo Building tag! %buildTag%
  - cmd: if NOT "%buildTag%"=="" git fetch
  - cmd: if NOT "%buildTag%"=="" git checkout %buildTag%
  - cmd: echo Building tag? %buildTag%

build_script:
  - go run build.go build
  - grunt release
  - go run build.go sha1-dist
  - cp dist/* .

artifacts:
  - path: grafana-*windows-*.*
    name: binzip
    type: zip

deploy:
  - provider: Environment
    name: GrafanaReleaseMaster
    on:
      buildType: master

  - provider: Environment
    name: GrafanaReleaseRelease
    on:
      buildType: release


