mysqltests:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: grafana_tests
    MYSQL_USER: grafana
    MYSQL_PASSWORD: password
  ports:
    - "3306:3306"

postgrestest:
  image: postgres:latest
  environment:
    POSTGRES_USER: grafanatest
    POSTGRES_PASSWORD: grafanatest
  ports:
    - "5432:5432"

