site_name: Grafana Documentation
#site_url: http://docs.grafana.com/
site_url: /
site_description: Documentation for Grafana, The Graphite and Influxdb dashboard and graph composer
site_favicon: img/fav32.png

dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/grafana/grafana/

docs_dir: sources

include_search: true

use_absolute_urls: true

# theme: docker
theme_dir: ./theme/mkdocs/
theme_center_lead: false

copyright: Copyright &copy; 2014-2015, Coding Instinct AB.
google_analytics: ['UA-47280256-1', 'grafana.org']


pages:

# Introduction:
- ['index.md', 'About', 'Grafana']
- ['installation/index.md', 'Installation', 'Install & Configure']
- ['installation/provisioning.md', 'Installation', 'Provisioning']
- ['installation/performance.md', 'Installation', 'Performance tips']
- ['installation/troubleshooting.md', 'Installation', 'Troubleshooting']

- ['guides/intro.md', 'User Guides', 'Getting started']
- ['guides/screencasts.md', 'User Guides', 'Screencasts']

- ['reference/graphs.md', 'Reference', 'Graph options']
- ['reference/annotations.md', 'Reference', 'Annotations']
- ['reference/time_range.md', 'Reference', 'Time range controls']
- ['reference/search.md', 'Reference', 'Dashboard Search']
- ['reference/templated_dashboards.md', 'Reference', 'Templated dashboards']
- ['reference/scripted_dashboards.md', 'Reference', 'Scripted dashboards']
- ['reference/playlist.md', 'Reference', 'Playlist']
- ['reference/export_import.md', 'Reference', 'Import & Export']

- ['datasources/graphite.md', 'Data Sources', 'Graphite guide']
- ['datasources/influxdb.md', 'Data Sources', 'InfluxDB guide']
- ['datasources/opentsdb.md', 'Data Sources', 'OpenTSDB guide']

- ['contributing/building_from_source.md', 'Project', 'Building from souce']
- ['contributing/cla.md', 'Project', 'Contributor License Agreement']

- ['jsearch.md', '**HIDDEN**']
